const APP_NAME = '10X';
const TATU_URL_HEAD = 'http://tatumzuka.co.tz/results?page=';
const searchText = 'Search';
const cancelText = 'Cancel';
const stopText = 'Stop';
const goText = 'Go';
const textFieldLabelText = 'Enter a winning draw';
const enterDrawHint = 'Draw';
const enterLimitHint = 'Page count';
const drawsText = 'Draws';
const rundownText = 'Run down';
const enterRundownLabelText = 'Rundown figure';
const computeRundownText = 'Compute';
